Fixes the startup error: (#1444)
InitError: Invalid listener for webRequest.onHeadersReceived

Came with a regression in d4a106e6eb5a8c54ab25d5d719941b33d8ef578d,
where the "onHeadersReceived" handler was removed from Events and
thus became "undefined" in the import (making it an invalid event handler).