test(e2e): retry messaging on failure
This changes aim to address e2e flakiness on Chrome browser due to the timing issue with background context.
`Promise was collected` potentially means that the context was close by any reason including garbage collector decision while waiting for the background script.

Relevant error lines:
```
[0-0] RUNNING in chrome(stable) - file:///tests/e2e/spec/onboarding.spec.js, file:///tests/e2e/spec/managed.spec.js, file:///tests/e2e/spec/main.spec.js, file:///tests/e2e/spec/zapped.spec.js, file:///tests/e2e/spec/adblocker.spec.js
[0-0] Error in "Managed Configuration."before all" hook: wrappedHook for "hides menu in panel when `disableUserControl` is enabled""
Error: WebDriver Bidi command "script.callFunction" failed with error: unknown error - Promise was collected
    at async sendMessage (file:///home/runner/work/ghostery-extension/ghostery-extension/tests/e2e/utils.js:53:18)
    at async setManagedConfig (file:///home/runner/work/ghostery-extension/ghostery-extension/tests/e2e/spec/managed.spec.js:28:3)
Driver Stack:
    at Error
    at     at new UnknownErrorException (<anonymous>:65:5630)
    at     at CommandProcessor.processCommand (<anonymous>:485:13788)
[0-0] Error in "Managed Configuration."after all" hook: wrappedHook for "applies custom filters added to `customFilters`""
Error: WebDriver Bidi command "script.callFunction" failed with error: unknown error - Promise was collected
    at async sendMessage (file:///home/runner/work/ghostery-extension/ghostery-extension/tests/e2e/utils.js:53:18)
    at async setManagedConfig (file:///home/runner/work/ghostery-extension/ghostery-extension/tests/e2e/spec/managed.spec.js:28:3)
Driver Stack:
    at Error
    at     at new UnknownErrorException (<anonymous>:65:5630)
    at     at CommandProcessor.processCommand (<anonymous>:485:13788)
```